### ISSUE TITLE
Lag/Locking from a Decently Populated Server

### ISSUE THREAD

**Issue by Fluxty** [gustav9797/PowerfulPerms#10] opened 2017-10-23 02:52 UTC
Hey, I run a Minecraft server with a playerbase of 300-500 concurrent players. Here are the issues we feel using PowerfulPerms:

- When using Redis to sync everything up, permission changes cause the entire network to disconnect (whilst pulling all over the place to refresh the cache from the db, I assume).

- Pulling player permissions from the database when they join _appears_ to cause lag in our fairly large database. Maybe query times?

- Reloading with /ppbungee reload, even with Redis disabled, causes Bungeecord to slow massively and results in time outs for half of our network multiple times.

**# Suggestions**:
One big suggestion I would have is to allow group parents to be specified with an optional server parameter, and to not cache those groups on servers where the parameter is not used. 

For example, we have a SkyBlock server, and for the SkyBlock server we have group named "SkyBlock". Every permission in the "SkyBlock" group has "SkyBlock" as the server parameter. The default group has this SkyBlock group as a parent. So when a player logs into Prison, or into a lobby, it's still pulling the SkyBlock group and checking the server parameter on every permission in there. If  group parents had an optional parent parameter, e.g. /pp group [group] parents add [group] [server], I feel this would improving permission lookups a lot, since you guys could just skip pulling that as an effective group if the server parameter doesn't match up. Does that make sense?

Thanks for your time, and sorry I did not have too much to give a detailed report. We are running the latest version of BungeeCord, most of our servers are on Spigot 1.8.8. Willing to answer any questions to get this figured out on our network 👍

**Comment by gustav9797** [comment] 2017-10-23 07:10
This is caused by both the UUID-column in all tables having string as datatype causing very slow indexing, and that large amounts of data is reloaded at once in the examples you've described. I was initially going to solve this for the PP v5 update but since that isn't happening I don't really know when it will be fixed.

**Comment by gustav9797** [comment] 2018-02-11 15:43
#1

**Closed as completed by gustav9797** 2018-02-11 15:43 UTC
Labels: bug, help wanted
